version: '3'

vars:
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.9.1'
  GOLANGCI_LINT_VERSION: 'v2.1.5'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'

tasks:
  install-formatters:
    desc: "Install gci and gofumpt to ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Installing gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Installing gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}
  
  install-golangci-lint:
    desc: "Installing golangci-lint to ./bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  format:
    desc: "Running gofumpt + gci"
    deps: [ install-formatters ]
    cmds:
      - |
        echo "🧼 Formatting gofumpt ..."
        find . -type f -name '*.go' -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Sorting imports gci ..."
        find . -type f -name '*.go' -exec {{.GCI}} write -s standard -s default -s "prefix(fuzzy-snake)" {} +

  lint:
    desc: "Running golangci-lint ..."
    deps: [ install-golangci-lint ]
    cmds:
      - '{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml' 

  default:
    cmds:
      - go run ./cmd/app.go